Ref handlers stock
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #23
Opened 2023-06-17 17:52 UTC by K1N88

рефакторинг сток хендлера

2023-06-18 15:52 UTC, AleksandrLyo requested changes

2023-06-18 15:52 UTC, AleksandrLyo commented on bot/handlers/stock.py
> +async def show_stock(update, context):
Эта вспомогательный колбэк мы его убираем, у нас там есть рабочий вариант remainder_parser_result, который только надо будет переименовать в stock_callback

2023-06-20 20:04 UTC, K1N88 commented on bot/handlers/stock.py
> +async def show_stock(update, context):
fix

2023-06-22 12:20 UTC, AleksandrLyo requested changes

2023-06-22 12:20 UTC, AleksandrLyo commented on bot/handlers/stock.py
> +    app.add_handler(CommandHandler("stock", stock_callback))
Хендлер не командный а срабатыеющий от сообщения пользователя
```suggestion
    app.add_handler(MessageHandler(filters.Regex(r'^\d+$'), stock_callback))
```

2023-06-22 15:02 UTC, K1N88 commented on bot/handlers/stock.py
> +    app.add_handler(CommandHandler("stock", stock_callback))
fix

2023-06-23 12:49 UTC, AleksandrLyo approved these changes

2023-06-23 12:49 UTC, AleksandrLyo commented
Все отлично, поправь конфликты и смержим

2023-06-24 06:50 UTC, K1N88 commented
конфликты исправил

2023-06-27 18:20 UTC, merged