Fix/acceptance rate
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #24
Opened 2023-06-17 22:17 UTC by JDoss86

Функции управления диалогом с кнопки Отслеживание коэффициента приемки WB перенесены в файл rate.py. 
Запуск функций в файл telegram_bot передается хендлером - rate_handlers.
Хендлер расположен над CallbackQueryHandler, т.к. перехватывает callback_data='acceptance_rate'.

2023-06-18 16:03 UTC, AleksandrLyo requested changes

2023-06-18 16:03 UTC, AleksandrLyo commented on bot/handlers/rate.py
> +async def acceptance_rate_info(update, context):
Давай этот колбэк уберем он у нас будет в в разделе меню

2023-06-18 16:03 UTC, AleksandrLyo commented on bot/handlers/rate.py
> +async def acceptance_rate_answer(update, context):
А этот переименуем в rate_callback, т.к сейчас все названия подгоняем под один стиль

2023-06-19 10:52 UTC, JDoss86 commented on bot/handlers/rate.py
> +async def acceptance_rate_info(update, context):
Вернул функцию в основной файл бота.

2023-06-19 10:52 UTC, JDoss86 commented on bot/handlers/rate.py
> +async def acceptance_rate_answer(update, context):
Переименовал функцию.

2023-06-19 13:36 UTC, AleksandrLyo requested changes

2023-06-19 13:36 UTC, AleksandrLyo commented on bot/telegram_bot.py
> -async def acceptance_rate_info(update, context):
Вот эту функцию не удаляй и поправь конфликты

2023-06-20 16:16 UTC, closed without merging