api_add
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #28
Opened 2023-06-19 18:22 UTC by TDShulga

добавила апи
Надеюсь все правильно

2023-06-20 16:03 UTC, AleksandrLyo requested changes

2023-06-20 16:03 UTC, AleksandrLyo commented on expert_system/expert_system/api/urls.py
>  from expert_system.data_handler.views import ButtonViewSet, TextViewSet
Старые заготовки не надо было удалять

2023-06-20 19:32 UTC, TDShulga commented on expert_system/expert_system/api/urls.py
>  from expert_system.data_handler.views import ButtonViewSet, TextViewSet
> Старые заготовки не надо было удалять

Я не удаляла, только добавила новые строки импорта библиотек, и новые пути единственное пришлось имена вьюх поменять, тк не понравились повторяющиеся имена

2023-06-21 09:24 UTC, TDShulga commented
Fix

2023-06-23 12:37 UTC, AleksandrLyo requested changes

2023-06-23 12:37 UTC, AleksandrLyo commented on expert_system/expert_system/api/serializers.py
> +        queryset=RequestPosition.objects.all(),
Параметр queryset не указывается в сериализаторе, его нужно перенести во вьюху, поправь во всех местах

2023-06-23 12:37 UTC, AleksandrLyo commented on expert_system/expert_system/api/serializers.py
> +            serializers.UniqueTogetherValidator(
В новой версии дрф валидация происходит вот таким образом, поправь во всех местах
```suggestion
    def validate(self, attrs):
        if RequestPosition.objects.filter(**attrs).exists():
            raise serializers.ValidationError("This object already exists")
        return attrs
```

2023-06-23 12:37 UTC, AleksandrLyo commented on expert_system/expert_system/data_handler/views.py
> +    serializer_class = RequestPositionSerializer
Сюда добавить queryset из сериализатора, поправь во всех местах

2023-06-23 12:37 UTC, AleksandrLyo commented on expert_system/expert_system/data_handler/views.py
> +    def perform_create(self, serializer):
Этот метод не нужен, объект создается и без него, поправь во всех местах

2023-06-23 12:37 UTC, AleksandrLyo commented on expert_system/expert_system/api/serializers.py
> +    text = serializers.CharFieldCharField(
Опечатка CharField два раза

2023-06-25 08:08 UTC, TDShulga commented
Fix. 
Извини заранее. Правила прямо здесь. Интернета нет с вечера пятницы, провайдер в понедельник вторник починит.

2023-06-28 13:23 UTC, merged