Fix/callback data
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #32
Opened 2023-06-20 18:36 UTC by AndreyFilippovich

2023-06-22 12:28 UTC, AleksandrLyo requested changes

2023-06-22 12:28 UTC, AleksandrLyo commented on bot/handlers/registration.py
> +from keyboards import subscribe_keyboard, start_keyboard, SUBSCRIBE
Тут у тебя уже будет импорт SUBSCRIBE не из клавиатур, а из колбэк даты

2023-06-22 12:28 UTC, AleksandrLyo commented on bot/keyboards.py
> +def subscribe_keyboard():
Не нужно использовать функции если внутри них нет логики, поменяй на обычные списки

2023-06-22 12:29 UTC, AleksandrLyo commented
Не создавай пожалуйста новые пиары, исправляй в этом

2023-06-23 09:51 UTC, AndreyFilippovich commented on bot/keyboards.py
> +def subscribe_keyboard():
Ты же мне говорил именно так сделать? Обратно переделать?

2023-06-23 12:52 UTC, AleksandrLyo commented on bot/keyboards.py
> +def subscribe_keyboard():
Андрей, я может тебе по ошибке сказал, если что извиняюсь. Суть такая если у тебя клавиатура без логики, то она создается списком, если в ней присутсвует логика вывода кнопок то это функция, у нас там никакой логики нет то нам нужен список

2023-06-28 13:32 UTC, closed without merging