just menu and repair functional
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #33
Opened 2023-06-21 06:27 UTC by Izrekatel

Переделал заново. Проверил функционал бота. Все работает. Пришлось переделать функцию rate_handlers в rate.py,

2023-06-22 12:47 UTC, AleksandrLyo requested changes

2023-06-22 12:47 UTC, AleksandrLyo commented on bot/handlers/menu.py
> +async def check_callback(update, context):
Избавляемся от этой функции, регистрируем хендлеры через CallbackQueryHandler с указанием патерна колбэка кнопки по которому этот хендлер вызывается

2023-06-22 12:47 UTC, AleksandrLyo commented on bot/handlers/menu.py
> +async def position_parser_expectations(update, context):
Эту функцию убираем она у нас в position.py

2023-06-22 12:47 UTC, AleksandrLyo commented on bot/handlers/menu.py
> +async def position_parser_result(update, context, result):
Эту функцию убираем она у нас в position.py

2023-06-22 12:47 UTC, AleksandrLyo commented on bot/handlers/menu.py
> +async def send_position_parser_subscribe(update, context):
Эту функцию убираем она у нас в position.py

2023-06-22 12:47 UTC, AleksandrLyo commented on bot/handlers/menu.py
> +async def remainder_parser_result(update, context):
Эту функцию убираем она у нас в stock.py

2023-06-23 05:43 UTC, Izrekatel commented on bot/handlers/menu.py
> +async def check_callback(update, context):
Done

2023-06-23 12:58 UTC, AleksandrLyo requested changes

2023-06-23 12:58 UTC, AleksandrLyo commented on bot/telegram_bot.py
>  from handlers import rate, registration
```suggestion
from handlers import menu, rate, registration
```

2023-06-23 12:58 UTC, AleksandrLyo commented on bot/telegram_bot.py
> +from handlers.menu import menu_handlers
Вот это лишнее

2023-06-23 12:58 UTC, AleksandrLyo commented on bot/telegram_bot.py
> +    menu_handlers(bot)
```suggestion
    menu.menu_handlers(bot)
```

2023-06-24 17:57 UTC, Izrekatel commented on bot/telegram_bot.py
> +from handlers.menu import menu_handlers
Не согласен. В проекте принято использовать единый подход к импортам. Я сделал ровно так как мы сделали ранее во всех файлах. Мы не импортировали их целиком, а импортировали из них методы, классы. Почему именно к хэндлерам такая избирательность? Это непрофессионально. Я видел, что коллеги импортировали файлы целиком, считаю что либо они весь проект с импортами поправят, либо свои импорты приведут в стандарт. А то получается один в лес, другой по дрова.

2023-06-28 00:07 UTC, merged