refact models, clean code
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #34
Opened 2023-06-21 08:21 UTC by Izrekatel

2023-06-22 12:37 UTC, AleksandrLyo requested changes

2023-06-22 12:37 UTC, AleksandrLyo commented on expert_system/expert_system/data_handler/models.py
> +class IdModel(models.Model):
Давай тогда назовем ее не IdModel, а Base и в эту модель перенесем поле из CreatedModel

2023-06-23 06:49 UTC, Izrekatel commented on expert_system/expert_system/data_handler/models.py
> +class IdModel(models.Model):
Переименовал, но поле add_time у нас не во всех моделях необходимо (к примеру в текстах и кнопках оно не нужно). Потому наоборот, CreatedModel  унаследовал от BaseModel

2023-06-23 13:00 UTC, AleksandrLyo commented on expert_system/expert_system/data_handler/models.py
> +class IdModel(models.Model):
Изменилось ТЗ, поэтому модели Текстов и Кнопок уберем, так что можешь спокойно сделать так как я попросил

2023-06-24 17:46 UTC, Izrekatel commented on expert_system/expert_system/data_handler/models.py
> +class IdModel(models.Model):
сделал

2023-07-06 12:20 UTC, closed without merging