add position_handlers
Studio-Yandex-Practicum/wildberries_bot_team_3 pull request #35
Opened 2023-06-25 06:04 UTC by K1N88

2023-06-26 12:15 UTC, AleksandrLyo requested changes

2023-06-26 12:15 UTC, AleksandrLyo commented on bot/handlers/position.py
> +async def position(update, context):
Эта не нужна, она нам уже не пригодится

2023-06-26 12:15 UTC, AleksandrLyo commented on bot/handlers/position.py
> +async def remainder_parser_result(update, context):
А вот это функция от остатков, тебе нужно было сюда добавить результат позиции position_parser_result

2023-06-26 12:17 UTC, AleksandrLyo requested changes

2023-06-26 12:17 UTC, AleksandrLyo commented on bot/telegram_bot.py
> +from handlers.position import position_handlers
И импортируем from handlers import position

2023-06-26 14:46 UTC, K1N88 commented on bot/telegram_bot.py
> +from handlers.position import position_handlers
fix

2023-06-27 10:51 UTC, AleksandrLyo commented
Еще предыдущие два коммента вдруг не заметил

2023-06-27 18:47 UTC, merged